%dev.quarkus.http.port=8090

# Force the Quarkus scheduler to use Unix cron syntax for CNCF compliance
quarkus.scheduler.cron-type=unix

quarkus.flow.runner.openapi.expand-workflows=true

quarkus.flow.messaging.defaults-enabled=true
quarkus.flow.tracing.enabled=true

# Inbound (Listens for events to start or resume workflows)
#mp.messaging.incoming.flow-in.auto.offset.reset=earliest
mp.messaging.incoming.flow-in.connector=smallrye-kafka
mp.messaging.incoming.flow-in.topic=flow-in
mp.messaging.incoming.flow-in.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
mp.messaging.incoming.flow-in.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Outbound (Publishes events emitted by the workflow)
mp.messaging.outgoing.flow-out.connector=smallrye-kafka
mp.messaging.outgoing.flow-out.topic=flow-out
mp.messaging.outgoing.flow-out.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
mp.messaging.outgoing.flow-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer



## Lifecycle events (Optional, if you want to listen to workflow lifecycle events)
## We will need to modify the IHM Tool so it can receive these events and handle it as the existing ones.

quarkus.flow.messaging.lifecycle-enabled=true
quarkus.flow.definitions.namespace.prefix=matrisk
quarkus.log.console.json.enabled=true

mp.messaging.outgoing.flow-lifecycle-out.connector=smallrye-kafka
mp.messaging.outgoing.flow-lifecycle-out.topic=flow-lifecycle-out
mp.messaging.outgoing.flow-lifecycle-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.flow-lifecycle-out.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer

# DEBUG events in the console
quarkus.log.category."io.quarkiverse.flow.messaging".level=DEBUG
# Change to DEBUG to increase tracing
uarkus.log.category."io.quarkiverse.flow".level=DEBUG
# Enabled it to increase tracing
quarkus.flow.tracing.enabled=true
